service: twitter-hate-speech-api
runtime: python
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
env: flex
#instance_class: F4_1G
#automatic_scaling:
#  min_instances: 2
#inbound_services:
#- warmup
resources:
  cpu: 2
  memory_gb: 5
  disk_size_gb: 20
#env: flex
#instance_class: F4_1G
runtime_config:
  python_version: 3.7
#manual_scaling:
#  instances: 2
env_variables:
  CLOUD_SQL_USERNAME: master
  CLOUD_SQL_PASSWORD: cs329s
  CLOUD_SQL_DATABASE_NAME: tweets_db
  CLOUD_SQL_CONNECTION_NAME: cs329s-final-project:us-west2:cs329s-tweet-database
  PYTHONHASHSEED: 0
beta_settings:
  cloud_sql_instances: cs329s-final-project:us-west2:cs329s-tweet-database
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301