service: twitter-hate-speech-api
runtime: python38
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
#env: flex
instance_class: F4_1G
resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 30